In [ ]:
import numpy as np

In [ ]:
# repeat the data
# num1 = np.array([1, 2, 3])
# num2 = np.repeat(num1, 3)

# print(num1)
# print(num2)

nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# num2 = np.repeat(nums, 3) # by default axis = 1 and 1d
# num2 = np.repeat(nums, 3, axis=1)
num2 = np.repeat(nums, 3, axis=0)

# print(nums)
print(num2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [ ]:
# list vs numpy
# list -> size, ref count, object type, object value, the data is not contiguous
list_1 = [10, 20, 'vasi']
list_2 = list_1

print(list_1, list_2)
# list_1[0] = 50
list_2[0] = 50
print(list_1, list_2)

print(id(list_1), id(list_2))

[10, 20, 'vasi'] [10, 20, 'vasi']
[50, 20, 'vasi'] [50, 20, 'vasi']
1394943131840 1394943131840


In [ ]:
num1 = 10
num2 = num1

print(num1, num2)
# num1 = 100
num2 = 100
print(num1, num2)
print(id(num1), id(num2))

10 10
10 100
1394856454736 1394856646096


In [ ]:
nums = np.array([1, 2, 3])
# print(nums)

# num = 'vasanth'
# num1 = int(10)
# print(num, num1, type(num))

vasanth 10 <class 'str'>


In [ ]:
# speed test
# a = np.random.randint(low=10, high=100, size=(3,4))
# a = np.random.uniform(low=10, high=100, size=(3,4))
# a = np.random.random(1000)
# print(a)

from timeit import default_timer as timer

a = np.random.random(1000)
b = np.random.random(1000)

l1 = list(a)
l2 = list(b)

def find_product():
    dot = 0
    for i in range(len(l1)):
        dot += l1[i] * l2[i]
    return dot

def find_dot():
    return np.dot(a, b)

start = timer()
for i in range(100000):
    find_product()
end = timer()
print(end - start)

start = timer()
for i in range(100000):
    find_dot()
end = timer()
print(end - start)

14.553620500000306
0.12142219999986992


In [ ]:
# slicing -> (start, end+1, step=1)
nums = np.array([10, 20, 30, 40, 50])

# print(nums[0], nums[1])
# print(nums[0:4])
# print(nums[4:1])
# print(nums[:3])
# print(nums[1:])
# print(nums[:])
# print(nums[0:4:2])
# print(nums[1::2])
# print(nums[0::2])

# print(nums[-3:-1])
# print(nums[-2:-5])
# print(nums[-5:-1:2])

# print(nums[4:1:-1])
# print(nums[:2:-1]) # if step is -ve then default starting pt is -1
# print(nums[:2: 1]) # if step is +ve then default starting pt is 0

[]


In [ ]:
# 2d array -> [(start: end+1: step), (start: end+1: step)] => [rows, cols] -> rows are default
nums = np.array([
    [11, 12, 13, 14, 15, 16, 17, 18],
    [21, 22, 23, 24, 25, 26, 27, 28],
])

# ---- multiple rows ------
# print(nums[:])
# print(nums[0:1])
# print(nums[0:2])
# print(nums[:1])
# print(nums[1:])
# print(nums[-1:])
# print(nums[-1::-1])


# 1 row multiple columns
# print(nums[0, 1:5])
# print(nums[1, -6:6])
# print(nums[-2, 2:-3])
# print(nums[-1, 2:-3])
# print(nums[1, -7:5:2])
# print(nums[-2, -3:-6])
# print(nums[0, :-7:1])
# print(nums[-2, 4:-4])

# multiple rows and multiple cols
# print(nums[:, 2:7])
# print(nums[:1, -6:4])
# print(nums[::-1, 2:-3])
# print(nums[-1:-2, 0:-7:-1])
# print(nums[::1, :5:2])

[[11 13 15]
 [21 23 25]]


In [ ]:
# change value using slicing
nums = np.array([
    [11, 12, 13, 14, 15, 16, 17, 18],
    [21, 22, 23, 24, 25, 26, 27, 28],
])

# nums[0][5] = 10
# nums[1, 3:5] = 20
nums[1, 3] = 75
print(nums)

[[11 12 13 14 15 16 17 18]
 [21 22 23 75 25 26 27 28]]


In [ ]:
# cross product
# n1 = np.array([4, 9, 12])
# n2 = np.array([10, 20, 30])

# print(np.cross(n1, n2))

# reshaping the array
# nums = np.array([1, 2, 3, 4, 5, 6])
# print(nums.shape)

# print(nums.reshape(2, 3))
# print(nums.reshape(3, 2))
# print(nums.reshape(2, 4)) # error


# 2d
nums = np.array([
    [1, 2, 3, 10],
    [4, 5, 6, 10],
    [7, 8, 9, 10]
])

# print(nums.shape)
# print(nums.reshape(2, 6))
# print(nums.reshape(4, 3))
# print(nums.reshape(6, 2))
# print(nums.reshape(12, 1))
# print(nums.reshape(1, 12))
# print(nums.reshape(2, 3))

[[ 1  2  3]
 [10  4  5]
 [ 6 10  7]
 [ 8  9 10]]


In [ ]:
# horizontal stack
n1 = np.array([1, 2, 3, 4])
n2 = np.array([5, 6, 7, 8])

# print(np.hstack([n1, n2, n1, n1, n2]))

# vertical stack
# print(np.vstack([n1, n2, n1, n1, n2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


In [ ]:
# splitting -> vertical splitting(default)
nums = np.array([
    [1, 2, 3, 4],
    [5, 6, 73, 8],
    [9, 110, 11 ,12],
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11 ,12]
])

# uniform splitting
# from pprint import pprint # pretty print
# pprint(np.vsplit(nums, 3))
# pprint(np.vsplit(nums, 3)[0])
# pprint(np.vsplit(nums, 3)[1])
# pprint(np.vsplit(nums, 3)[2])


# pprint(np.split(nums, 2))
# pprint(np.split(nums, 2)[0])
# pprint(np.split(nums, 2)[1])

# pprint(np.split(nums, 4))  # error

# custom cut
# pprint(np.split(nums, [1, 3]))
# pprint(np.split(nums, [1, 3])[0])
# pprint(np.split(nums, [1, 3])[1])
# pprint(np.split(nums, [1, 3])[2])

# pprint(np.split(nums, [2, 4]))
# pprint(np.split(nums, [2, 4])[0])
# pprint(np.split(nums, [2, 4])[1])
# pprint(np.split(nums, [2, 4])[2])

# pprint(np.split(nums, [1, 3, 4]))
# pprint(np.split(nums, [1, 3, 4])[0])
# pprint(np.split(nums, [1, 3, 4])[1])
# pprint(np.split(nums, [1, 3, 4])[2])
# # pprint(np.split(nums, [1, 3, 4])[3])

# # pprint(np.split(nums, [1, 4, 3]))
# pprint(np.split(nums, [1, 4, 3])[0])
# pprint(np.split(nums, [1, 4, 3])[1])
# pprint(np.split(nums, [1, 4, 3])[2])
# pprint(np.split(nums, [1, 4, 3])[3])

In [ ]:
# horizontal splitting
nums = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11 ,12]
])

# uniformly
# pprint(np.hsplit(nums, 2))
# pprint(np.hsplit(nums, 2)[0])
# pprint(np.hsplit(nums, 2)[1])

# pprint(np.hsplit(nums, 3)) # error

# custom
# print(np.hsplit(nums, [1, 3]))
# print(np.hsplit(nums, [1, 3])[0])
# print(np.hsplit(nums, [1, 3])[1])
# print(np.hsplit(nums, [1, 3])[2])

In [ ]:
# comparison operators -> bool -> boolean matrix
nums = np.array([
    [1, 2, 10, 4],
    [4, 5, 6, 8]
])

print(nums > 5)
# print(nums >= 5)
# print(nums < 5)
# print(nums <= 5)
# print(nums == 5)
# print(nums != 5)

# filtering the data based on condition
print(nums[nums > 5])

# print(nums % 2 == 0)
# even_nos = (nums % 2 == 0)
# print(nums % 2 == 0)
# odd_nos = (nums % 2 != 0)
# print(nums[even_nos])

[[False False  True False]
 [False False  True  True]]
[10  6  8]


In [ ]:
# linear algebra -> det (ad - bc)
nums = np.array([
    [1, 2],
    [4, 5]
])

# print(np.linalg.det(nums))

-2.9999999999999996


In [ ]:
# inverse of matrix -> 1/det(nums) * adj(nums)
nums = np.array([
    [1, 2],
    [4, 5]
])

print(np.linalg.inv(nums))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [ ]:
# 3.000000000000000000000000000000000005 - 2.000000000000000000000007

1.0

In [ ]:
# transpose
nums = np.array([
    [1, 2, 3, 4],
    [4, 5, 6, 7]
])

# print(np.transpose(nums))

# sorting
nums = np.array([
    [1, 310, 6, 87],
    [22, 70, 66, 34],
    [656, 99, 95, 65]
])

# print(np.sort(nums))
# print(np.sort(nums, axis=0))
# print(np.sort(nums, axis=1))

[[  1  70   6  34]
 [ 22  99  66  65]
 [656 310  95  87]]


In [ ]:
# broadcasting
a = np.array([
    [1, 310, 6, 87],
    [22, 70, 66, 34],
    [656, 99, 95, 65]
])

b = np.array([1, 2, 3, 4])

print(a + b)

[[  2 312   9  91]
 [ 23  72  69  38]
 [657 101  98  69]]


In [ ]:
# statistics
nums = np.array([
    [1, 2, 3],
    [4, 15, 26],
    [7, 8, 10]
])

# print(np.mean(nums))
# print(np.median(nums))
# print(np.std(nums)) # std deviation
print(np.var(nums)) # variance

55.80246913580247


In [ ]:
# load files in numpy
values = np.genfromtxt('./data.txt', delimiter=',')
pprint(values)
# print(type(values))

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])
