In [ ]:
# operators, functions, loops, conditional statements, collections
# OOPs -> encapsulation, inheritance, abstraction and polymorphism

In [ ]:
# NUMPY -> Numerical Python -> 30k - 300k
# collect the data -> preprocess(clean) the data

In [ ]:
# n dimensions

# 1d -> row or col
heros = ['srk', 'vijay', 'ajith', 'yash', 'ntr']
# print(heros)

# 2d -> row and col
pairs = [
    ['srk', 'deepika', 'sidharth'],
    ['vijay', 'rashmika', 'vamshi'],
    ['ntr', 'alia', 'ssr']
]
print(pairs[0], pairs[1])

['srk', 'deepika', 'sidharth'] ['vijay', 'rashmika', 'vamshi']


In [ ]:
# 3d volume of obj -> l * b * h

In [ ]:
# pip install numpy
# conda install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy
print(numpy.__version__)

1.21.5


In [ ]:
nums = [1, True, 10.5, 'das']
print(nums)

[1, True, 10.5, 'das']


In [ ]:
# Numpy -> one datatype
import numpy as np

list_nums = [1, 2, 3]
nums = np.array(list_nums)
print(nums, type(nums))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
import numpy as np

# nums = np.array([1, 2, 3, 4, 5], dtype='int64')
# print(nums)
# print(type(nums), nums.dtype)
# print(nums.shape)
# print(nums.ndim)
# print(nums.size, len(nums))
# print(nums.itemsize)
# print(np.sum(nums))

15


In [ ]:
# def display(name, age):
#     print(f'my name is {name} and age is {age}')

# display(age = 5, name = 'sandhya')

my name is sandhya and age is 5


In [ ]:
# 2d
nums = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# print(nums)
# print(type(nums), nums.dtype)
# print(nums.shape)
# print(nums.ndim)
# print(nums.size, len(nums))
# print(nums.itemsize)
# print(np.sum(nums))


45


In [ ]:
# 3d
nums = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [4, 5, 6],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [4, 5, 6]
    ]
])

# print(nums)
# print(type(nums), nums.dtype)
# print(nums.shape)
# print(nums.ndim)
# print(nums.size, len(nums))
# print(nums.itemsize)
# print(np.sum(nums))

(3, 2, 3)


In [ ]:
nums = np.array([10, 20, 30])
# print(nums[0], nums[1], nums[2], nums[3])
# print(nums[-1], nums[-2], nums[-3], nums[-4])

In [ ]:
nums = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# print(nums[0], nums[1], nums[2])
# print(nums[-1], nums[-2], nums[-3])
# print(nums[0][0], nums[0][1], nums[2][0])
# 7
# print(nums[2][0], nums[-1][0], nums[2][-3], nums[-1][-3])
# 5
# print(nums[-2][-2], nums[-2][1], nums[1][-2], nums[1][1])
print(nums[-2, -2], nums[-2, 1], nums[1, -2], nums[1, 1])

5 5 5 5


In [ ]:
# # 3d
# nums = np.array([
#     [
#         [1, 2, 3],
#         [4, 5, 6]
#     ],
#     [
#         [4, 5, 6],
#         [4, 5, 6]
#     ],
#     [
#         [7, 8, 19],
#         [4, 5, 6]
#     ]
# ])

# print(nums[2][0][2], nums[-1][-2][-1])
# print(nums[2, 0, 2], nums[-1, -2, -1])

19 19
19 19


In [ ]:
# # zeros
# nums = np.zeros((5, 5), dtype='int64') # dtype=float
# print(nums)

# # ones
# nums = np.ones((5, 5), dtype='int64')
# print(nums)

# full
# nums = np.full((5, 5), 20)
# print(nums)

# # identity matrix
# nums = np.identity(4, dtype='int64')
# print(nums)

# nums = np.array([
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ])
# print(np.sum(nums))
# print(np.sqrt(nums))


# # full_like
# nums_2 = np.full_like(nums, 0)
# print(nums_2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# ndmin -> nd minimum
# nums = np.array([1, 2, 3], ndmin=2)
# print(nums)

# nums = np.array([
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ], ndmin=3)

# print(nums)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# list_nums = [1, 2, 3]
# print(list_nums + 4)

# arithmetic operations
nums = np.array([
    [1, 2],
    [3, 4]
])

# print(nums + 5)
# print(5 + nums)
# print(nums - 5)
# print(5 - nums)
# print(nums * 5)
# print(5 * nums)
# print(nums / 5)
# print(5 / nums)
# print(nums // 5)
# print(5 // nums)
# print(nums ** 5)
# print(5 ** nums)

[[   1   32]
 [ 243 1024]]
[[  5  25]
 [125 625]]


In [ ]:
# addtion
nums1 = np.array([
    [1, 2],
    [3, 4]
])

nums2 = np.array([
    [1, 2],
    [3, 4]
])

# shape should be same
# print(nums1 + nums2)
# print(nums1 - nums2)
# print(nums1 * nums2)
# print(nums1 / nums2)
# print(nums1 // nums2)
# print(nums1 ** nums2)

# dot product
# print(np.dot(nums1, nums2))

[[  1   4]
 [ 27 256]]
